version: '3'
services:
  web:
    labels:
      - traefik.backend=uk.co.davidsouthgate.omcrs
      - traefik.frontend.rule=Host:omcrs.davidsouthgate.co.uk
      - traefik.docker.network=traefik
      - traefik.port=80
      - traefik.frontend.priority=10
      - traefik.frontend.redirect.entryPoint=https
    networks:
      - traefik
networks:
  traefik:
    external: true
